spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

  flyway:
    enabled: true

omega:
  chat:
    relay:
      host: localhost
      port: 61613
